export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST";
export const EDIT_TASK = "EDIT_TASK";
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE";

export const GLOBAL_SEARCH_REQUEST = "GLOBAL_SEARCH_REQUEST";
export const GLOBAL_SEARCH = "GLOBAL_SEARCH";
export const GLOBAL_SEARCH_FAILURE = "GLOBAL_SEARCH_FAILURE";

export const SORT_TASK_LIST_REQUEST = "SORT_TASK_LIST_REQUEST";
export const SORT_TASK_LIST = "SORT_TASK_LIST";
export const SORT_TASK_LIST_FAILURE = "SORT_TASK_LIST_FAILURE";

export const GROUP_TASK_LIST_REQUEST = "GROUP_TASK_LIST_REQUEST";
export const GROUP_TASK_LIST = "GROUP_TASK_LIST";
export const GROUP_TASK_LIST_FAILURE = "GROUP_TASK_LIST_FAILURE";
